Revert changes to main and toml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -38,12 +38,20 @@ jobs:
         uses: dtolnay/rust-toolchain@stable
         with:
           targets: ${{ matrix.target }}
+      
+      - name: Install GCC
+        run: |
+          sudo apt update
+          sudo apt install -y gcc-11 g++-11
+          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100
+          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
 
       - name: Install CUDA (Only for CUDA Builds)
         if: matrix.features == 'cuda'
         uses: Jimver/cuda-toolkit@v0.2.11
         with:
           cuda: '12.1.0'
+          method: 'network'  # Avoids using pre-cached
 
       - name: Set up CUDA environment (Only for CUDA Builds)
         if: matrix.features == 'cuda'
@@ -53,6 +61,11 @@ jobs:
           echo "CUDA_HOME=/usr/local/cuda" >> $GITHUB_ENV
           echo "LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV
           echo "CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda" >> $GITHUB_ENV
+
+      - name: Validate CUDA Installation
+        if: matrix.features == 'cuda'
+        run: |
+          nvcc --version || (echo "CUDA installation failed" && exit 1)
 
       - name: Rust Cache
         uses: Swatinem/rust-cache@v2
